[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "24"

# Optional: force clean URLs
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

# Optional: if you have a SPA route you want to fallback to
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
#   force = true