name: Build & Deploy Eleventy to GitHub Pages

on:
  push:
    branches: [ main ]   # or your default
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install deps
        run: npm install

      - name: Build Eleventy
        run: npx @11ty/eleventy

      # Optional: ensure Jekyll is disabled on Pages
      - name: Disable Jekyll
        run: touch _site/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
